---
name: sample job name
description: A job that runs my custom shell script for server maintenance.
runNumber: 0
lastSuccessfulRun: 0
lastFailedRun: 0
allowHttpRun: True
trigger:
  cron: "* * * * *"
steps:
  sh:
    - cd ~/prog/deploymentscripts/util-server
    - make deploy
    - mycustomshellscript.sh --some-args
    - make clean
    - ls -al
